name: Test Automation - Testing Pre-Merge

on: pull_request

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install yarn
        run: npm install bun -g

      - name: Install all dependencies 
        run: bun install

      - name: Run tests
        run: bun run test:e2e --coverage
